version: "3.1"

services:
  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/ #mount application source
    ports:
      - 3031:3031
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - "db"
    tty: true
    networks:
      - pixiv-gans-network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf #mount configuration
      - ./nginx/log:/var/log/nginx #nginx logging
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - "db"
    tty: true
    networks:
      - pixiv-gans-network

  db:
    build: ./db
    hostname: my-mysql
    env_file:
      - ./env_file.env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d #initialize db
      - ./db/mysql_data:/var/lib/mysql #permanent db
      - ./db/conf.d:/etc/mysql/conf.d  #mount configuration
    tty: true
    networks:
      - pixiv-gans-network


networks:
    pixiv-gans-network:
        external: true
