version: '3.1'

services:
  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/ #アプリケーション共有
    ports:
      - 3031:3031
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    networks:
      - pixiv-gans-network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf #設定ファイル共有
      - ./nginx/log:/var/log/nginx #ログ出力
    ports:
      - 5000:80
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    networks:
      - pixiv-gans-network

  db:
    build: ./db
    restart: always
    hostname: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d #DB初期化
      - ./db/mysql_data:/var/lib/mysql #データ永続化
      - ./db/conf.d:/etc/mysql/conf.d  #設定ファイル共有
    tty: true
    networks:
      - pixiv-gans-network


networks:
    pixiv-gans-network:
        external: true
